version: '3.8'

volumes:
  postgres_data: {}

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
      - kafka
      - zookeeper
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres_db:5432/romashko_db'

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  postgres_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=romashko_db
      - POSTGRES_USER=crypto_tracker
      - POSTGRES_PASSWORD=crypto_tracker
    ports:
      - 5432:5432
    networks:
      - default



networks:
  default: