version: '3.8'

volumes:
  postgres_data: {}

services:
  app:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - postgres_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://postgres_db:5432/romashko_db'

  postgres_db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=romashko_db
      - POSTGRES_USER=crypto_tracker
      - POSTGRES_PASSWORD=crypto_tracker
    ports:
      - 5432:5432
    networks:
      - default



networks:
  default: